redirects:
  introduction: /overview/the-essentials.md
  about/five-minute-quickstart: /getting-started/five-minute-quickstart.md
  faq/how-do-I-avoid-duplicates-in-imports: /faq/how-do-I-avoid-duplicating-data.md
  faq/how-do-i-add-images-to-my-elements: /guides/images.md
  faq/how-do-i-change-element-shape: /guides/shapes.md
  faq/how-do-i-change-element-shapes-from-circles-to-squares: /faq/how-do-i-change-element-shape.md
  faq/how-do-i-decorate-a-single-element-or-connection: /guides/direct-decorations.md
  faq/how-do-i-delete-a-project: /faq/how-do-i-delete-a-project-map-or-view.md
  faq/how-to-add-background-image: /guides/images.md
  faq/how-to-add-contributors: /overview/collaboration.md#add-a-contributor
  faq/how-to-scale-elements-no-text-size-change: /faq/how-do-i-control-label-size-while-scaling-element-size.md
  faq/who-is-allowed-to-edit-my-project: /overview/actions-and-permissions.md
  getting-started/adding-a-collaborator: /getting-started/overview.md#adding-a-collaborator-permalink
  getting-started/basic-vs-advanced-editor: /overview/view-editors.md
  getting-started/building-your-first-map: /getting-started/overview.md#building-your-first-map-permalink
  getting-started/decorations: /getting-started/overview.md#decorations-permalink
  getting-started/five-minute-quickstart: /#five-minute-quickstart
  getting-started/hiding-elements-connections: /getting-started/overview.md#hiding-elements-connections-permalink
  getting-started/introduction: /getting-started/first-steps.md
  getting-started/overview: /getting-started/first-steps.md
  getting-started/picking-a-template: /getting-started/overview.md#picking-a-template-permalink
  getting-started/projects-vs-maps-vs-views.md: /overview/data-architecture.md
  guides/advanced-settings: /guides/settings-reference.md
  guides/attributes: /guides/fields.md
  guides/basics/fields: /guides/fields.md
  guides/collaboration: /overview/collaboration.md
  guides/controls/field-filter-control: /guides/controls/filter-control.md
  guides/controls/field-showcase-control: /guides/controls/showcase-control.md
  guides/controls/showcase-toggle-control: /guides/controls/showcase-control.md
  guides/data-editor: /guides/table.md
  guides/default-settings: /guides/default-view-settings.md
  guides/embeds: /guides/share-and-embed.md
  guides/index: /guides/guides.md
  guides/layout: /guides/layouts.md
  guides/organizations: /guides/pro-workspaces.md
  guides/perspectives-advanced: /guides/views-advanced.md
  guides/perspectives: /guides/views.md
  guides/project-architecture: /overview/kumus-architecture.md
  guides/sharing: /guides/embeds.md
  guides/snap-to: /guides/layouts/snap-to.md
  guides/views-advanced: /overview/view-editors.md#advanced-editor
  guides/wizard: /guides/quick-actions.md
  introduction: /overview/the-essentials.md
  overview/accounts-and-plans: /overview/accounts-and-workspaces.md
  overview/basic-vs-advanced-editor: /overview/view-editors.md
  overview/data-architecture: /overview/kumus-architecture.md
  overview/personal-and-organization-accounts: /overview/accounts-and-plans.md
  overview/the-essentials: /getting-started/first-steps.md
